EasyPlan/Controllers/JornadaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EasyPlan.Models;

namespace EasyPlan.Controllers
{
    public class JornadaController : Controller
    {
        private easyplanEntities db = new easyplanEntities();

        // GET: Jornada
        public ActionResult Index()
        {
            var tbl_Jornada = db.Tbl_Jornada.Include(t => t.Tbl_Trabajador);
            return View(tbl_Jornada.ToList());
        }

        // GET: Jornada/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Jornada tbl_Jornada = db.Tbl_Jornada.Find(id);
            if (tbl_Jornada == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Jornada);
        }

        // GET: Jornada/Create
        public ActionResult Create()
        {
            ViewBag.CedulaTra = new SelectList(db.Tbl_Trabajador, "CedulaTra", "Nombre");
            return View();
        }

        // POST: Jornada/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idJornada,CedulaTra,TipoJornada,HoraInicio,HoraFin,PrecioHoraRegular,PrecioHoraExtra,CantidadHorasRegulares,CantidadHorasExtras,ValorTotalHoraExtra,ValorTotalHorasRegulares,PrecioDia,UnidadMedida,PrecioUnidadMedida,ValorTotalUnidadMedida,PrecioMetro,PrecioPaquete,LaborExtra,PrecioLaborExtra,FechaJornada,SalarioJornada,Observacion")] Tbl_Jornada tbl_Jornada)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Jornada.Add(tbl_Jornada);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CedulaTra = new SelectList(db.Tbl_Trabajador, "CedulaTra", "Nombre", tbl_Jornada.CedulaTra);
            return View(tbl_Jornada);
        }

        // GET: Jornada/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Jornada tbl_Jornada = db.Tbl_Jornada.Find(id);
            if (tbl_Jornada == null)
            {
                return HttpNotFound();
            }
            ViewBag.CedulaTra = new SelectList(db.Tbl_Trabajador, "CedulaTra", "Nombre", tbl_Jornada.CedulaTra);
            return View(tbl_Jornada);
        }

        // POST: Jornada/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idJornada,CedulaTra,TipoJornada,HoraInicio,HoraFin,PrecioHoraRegular,PrecioHoraExtra,CantidadHorasRegulares,CantidadHorasExtras,ValorTotalHoraExtra,ValorTotalHorasRegulares,PrecioDia,UnidadMedida,PrecioUnidadMedida,ValorTotalUnidadMedida,PrecioMetro,PrecioPaquete,LaborExtra,PrecioLaborExtra,FechaJornada,SalarioJornada,Observacion")] Tbl_Jornada tbl_Jornada)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Jornada).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CedulaTra = new SelectList(db.Tbl_Trabajador, "CedulaTra", "Nombre", tbl_Jornada.CedulaTra);
            return View(tbl_Jornada);
        }

        // GET: Jornada/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Jornada tbl_Jornada = db.Tbl_Jornada.Find(id);
            if (tbl_Jornada == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Jornada);
        }

        // POST: Jornada/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Jornada tbl_Jornada = db.Tbl_Jornada.Find(id);
            db.Tbl_Jornada.Remove(tbl_Jornada);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EasyPlan/Views/Jornada/Create.cshtml
@model EasyPlan.Models.Tbl_Jornada

@{
    ViewBag.Title = "Create";

}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tbl_Jornada</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CedulaTra, "CedulaTra", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CedulaTra", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CedulaTra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoJornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoJornada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoJornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraInicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraFin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioHoraRegular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioHoraRegular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioHoraRegular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioHoraExtra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioHoraExtra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioHoraExtra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CantidadHorasRegulares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CantidadHorasRegulares, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantidadHorasRegulares, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CantidadHorasExtras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CantidadHorasExtras, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantidadHorasExtras, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorTotalHoraExtra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotalHoraExtra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotalHoraExtra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorTotalHorasRegulares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotalHorasRegulares, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotalHorasRegulares, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioDia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioDia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioDia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadMedida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadMedida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnidadMedida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioUnidadMedida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioUnidadMedida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioUnidadMedida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorTotalUnidadMedida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotalUnidadMedida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotalUnidadMedida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioMetro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioMetro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioMetro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioPaquete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioPaquete, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioPaquete, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaborExtra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LaborExtra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LaborExtra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrecioLaborExtra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioLaborExtra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioLaborExtra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaJornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaJornada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaJornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SalarioJornada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SalarioJornada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SalarioJornada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EasyPlan/Views/Jornada/Delete.cshtml
@model EasyPlan.Models.Tbl_Jornada

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tbl_Jornada</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoJornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoJornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioHoraRegular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioHoraRegular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioHoraExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioHoraExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadHorasRegulares)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadHorasRegulares)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadHorasExtras)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadHorasExtras)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotalHoraExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotalHoraExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotalHorasRegulares)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotalHorasRegulares)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioDia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioDia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnidadMedida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnidadMedida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioUnidadMedida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioUnidadMedida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotalUnidadMedida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotalUnidadMedida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioMetro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioMetro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioPaquete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioPaquete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaborExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaborExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioLaborExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioLaborExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaJornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaJornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalarioJornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalarioJornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Trabajador.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Trabajador.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EasyPlan/Views/Jornada/Details.cshtml
@model EasyPlan.Models.Tbl_Jornada

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tbl_Jornada</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoJornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoJornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioHoraRegular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioHoraRegular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioHoraExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioHoraExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadHorasRegulares)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadHorasRegulares)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadHorasExtras)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadHorasExtras)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotalHoraExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotalHoraExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotalHorasRegulares)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotalHorasRegulares)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioDia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioDia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnidadMedida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnidadMedida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioUnidadMedida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioUnidadMedida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotalUnidadMedida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotalUnidadMedida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioMetro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioMetro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioPaquete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioPaquete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LaborExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LaborExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecioLaborExtra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecioLaborExtra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaJornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaJornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalarioJornada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalarioJornada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tbl_Trabajador.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tbl_Trabajador.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idJornada }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EasyPlan/Views/Jornada/Index.cshtml
@model IEnumerable<EasyPlan.Models.Tbl_Jornada>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDemo.cshtml";
}

 
<div class="card text-center">

    <div class="card-body">
        <img src="~/Content/logo.jpg" />
        <h5 class="card-title">Journeys</h5>
        <a href="@Url.Action("Create","Jornada")" class="btn btn-primary"> Add New </a>
    </div>
</div>
<table class="table table-dark" style="text-align:center">
    <thead>
        <tr>
            <th scope="col">
                Type
            </th>
            <th scope="col">
                Worker
            </th> 
            <th scope="col">
                Day
            </th>
            <th scope="col">
                Value
            </th>
            <th scope="col"> Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TipoJornada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tbl_Trabajador.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalarioJornada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Observacion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idJornada }) |
                @Html.ActionLink("Details", "Details", new { id = item.idJornada }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.idJornada })
            </td>
        </tr>
        }
    </tbody>
</table>