EasyPlan/Controllers/TrabajadorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EasyPlan.Models;

namespace EasyPlan.Controllers
{
    public class TrabajadorController : Controller
    {
        private easyplanEntities db = new easyplanEntities();

        // GET: Trabajador
        public ActionResult Index()
        {
            return View(db.Tbl_Trabajador.ToList());
        }
        public ActionResult IndexDemo()
        {
            return View(db.Tbl_Trabajador.ToList());
        }
        // GET: Trabajador/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Trabajador tbl_Trabajador = db.Tbl_Trabajador.Find(id);
            if (tbl_Trabajador == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Trabajador);
        }
 

        // GET: Trabajador/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Trabajador/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CedulaTra,Nombre,Apellido,Puesto,Edad,Telefono,Correo,FechaNacimiento,Nacionalidad,NumEmpleado,Ciudad,Direccion,FechaEmpleo,Empleador,FechaDespido,InicioIncapacidad,FinalIncapacidad,Padecimientos,Estado,Observacion")] Tbl_Trabajador tbl_Trabajador)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Trabajador.Add(tbl_Trabajador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Trabajador);
        }

        // GET: Trabajador/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Trabajador tbl_Trabajador = db.Tbl_Trabajador.Find(id);
            if (tbl_Trabajador == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Trabajador);
        }

        // POST: Trabajador/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CedulaTra,Nombre,Apellido,Puesto,Edad,Telefono,Correo,FechaNacimiento,Nacionalidad,NumEmpleado,Ciudad,Direccion,FechaEmpleo,Empleador,FechaDespido,InicioIncapacidad,FinalIncapacidad,Padecimientos,Estado,Observacion")] Tbl_Trabajador tbl_Trabajador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Trabajador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Trabajador);
        }

        // GET: Trabajador/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Trabajador tbl_Trabajador = db.Tbl_Trabajador.Find(id);
            if (tbl_Trabajador == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Trabajador);
        }

        // POST: Trabajador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Tbl_Trabajador tbl_Trabajador = db.Tbl_Trabajador.Find(id);
            db.Tbl_Trabajador.Remove(tbl_Trabajador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EasyPlan/Views/Trabajador/Create.cshtml
@model EasyPlan.Models.Tbl_Trabajador

@{
    ViewBag.Title = "Create";

}
 

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="container">
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("ID worker", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CedulaTra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CedulaTra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Roll", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Puesto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Puesto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Age", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Phone", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("E-mail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Date of birth", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nationality", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ciudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Direction", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Date of employment", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEmpleo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEmpleo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Employer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empleador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empleador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Date of dismissal", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDespido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDespido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Onset of disability", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InicioIncapacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InicioIncapacidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("End of disability", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FinalIncapacidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinalIncapacidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ailments", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Padecimientos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Padecimientos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("State", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Observation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("<< Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EasyPlan/Views/Trabajador/Delete.cshtml
@model EasyPlan.Models.Tbl_Trabajador

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tbl_Trabajador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumEmpleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEmpleo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEmpleo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDespido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDespido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InicioIncapacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InicioIncapacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalIncapacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalIncapacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Padecimientos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Padecimientos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EasyPlan/Views/Trabajador/Details.cshtml
@model EasyPlan.Models.Tbl_Trabajador

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tbl_Trabajador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puesto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puesto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumEmpleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciudad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEmpleo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEmpleo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDespido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDespido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InicioIncapacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InicioIncapacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalIncapacidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalIncapacidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Padecimientos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Padecimientos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CedulaTra }) |
    @Html.ActionLink("Back to List", "Index")
</p>



<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

EasyPlan/Views/Trabajador/Index.cshtml
@model IEnumerable<EasyPlan.Models.Tbl_Trabajador>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDemo.cshtml";
}
 



<div class="card text-center">
 
    <div class="card-body">
        <img src="~/Content/logo.jpg" />
        <h5 class="card-title">Workers</h5>
        <a href="@Url.Action("Create","Trabajador")" class="btn btn-primary"> Add New </a>
    </div>
</div>


 
 
<table class="table table-dark" style="text-align:center">
    <thead>
        <tr>

            <th scope="col">
                N° Employee
            </th>
            <th scope="col">
                Name
            </th>
            <th scope="col">
                E-mail
            </th>
            <th scope="col">
                City
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th> Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr class="datos">
            <td>
                @Html.DisplayFor(modelItem => item.NumEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ciudad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                <button type="button" class="btn btn-success">
                    <span style="color:#FF0000">@Html.ActionLink("Edit", "Edit", new { id = item.CedulaTra })</span>
                </button>
                <button type="button" class="btn btn-info">
                    @Html.ActionLink("Details", "Details", new { id = item.CedulaTra })
                </button>
                <button type="button" class="btn btn-danger">
                    @Html.ActionLink("Delete", "Delete", new { id = item.CedulaTra })
                </button>
            </td>
        </tr>
        }
    </tbody>
</table>

EasyPlan/Views/Trabajador/IndexDemo.cshtml
@model IEnumerable<EasyPlan.Models.Tbl_Trabajador>

@{
    ViewBag.Title = "IndexDemo";
    Layout = "~/Views/Shared/_LayoutDemo2.cshtml";
}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Puesto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Correo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumEmpleado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ciudad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaEmpleo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Empleador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaDespido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InicioIncapacidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FinalIncapacidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Padecimientos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Observacion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Puesto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Correo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nacionalidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumEmpleado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ciudad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaEmpleo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Empleador)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaDespido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.InicioIncapacidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FinalIncapacidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Padecimientos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Observacion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CedulaTra }) |
            @Html.ActionLink("Details", "Details", new { id=item.CedulaTra }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CedulaTra })
        </td>
    </tr>
}

</table>